version: '3'

services:
  nginx:
    image: jonasal/nginx-certbot:6.0.1-nginx1.29.4
    container_name: nginx_proxy
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: ${certbot_email}
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:                                    # Storage can be either a
      - nginx_secrets:/etc/letsencrypt          # Docker managed volume (see list at the bottom)
      - ./config/default.d:/etc/nginx/default.d    # or a host mount with a relative or full path.
    networks:
      - noticeboard-api_noticeboard-network

networks:
  noticeboard-api_noticeboard-network:
    external: true

volumes:
  nginx_secrets: