services:
  nginx:
    image: jonasal/nginx-certbot:6.0.1-nginx1.29.4
    container_name: nginx_proxy
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d 
    networks:
      - noticeboard-api_noticeboard-network

networks:
  noticeboard-api_noticeboard-network:
    external: true

volumes:
  nginx_secrets: